# 开发环境
# 配置管理中心 项目配置
spring:
  cloud:
    config:
      server:
        # git相关配置配置
        git:
          uri: ssh://config-dev@172.16.15.198:29418/test-config-repo.git
          username: config-dev
          password: config@123456
          default-label: master #配置文件分支
          search-paths: config-dev  #配置文件所在根目录

# 注册中心配置
eureka:
  instance:
    hostname: localhost
    port: 4001
    application:
      name: cloud-center
  client:
    service-url:
      # eureka 访问地址  注：/eureka 不能丢，不能换 不能丢，不能换 不能丢，不能换
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/${eureka.instance.application.name}/eureka
      #false 表示不向注册中心注册自己
      register-with-eureka: true
      #false 表示不从注册中心获取注册信息
      fetch-registry: true
      # 注册服务的时候使用ip地址，ip地址从host里面找。
      prefer_ip_address: true